name: hare
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backcall=0.2.0
  - ca-certificates=2024.12.14
  - certifi=2024.2.2
  - decorator=5.1.1
  - entrypoints=0.4
  - ipython_genutils=0.2.0
  - jedi=0.19.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnsl=2.0.1
  - libsodium=1.0.18
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - openssl=3.4.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - ptyprocess=0.7.0
  - python=3.7.12
  - python-dateutil=2.9.0
  - python_abi=3.7
  - pyzmq=24.0.1
  - readline=8.2
  - six=1.16.0
  - sqlite=3.47.2
  - tk=8.6.13
  - tornado=6.2
  - traitlets=5.9.0
  - wheel=0.42.0
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - absl-py==2.0.0
      - aiofiles==22.1.0
      - aiosqlite==0.19.0
      - anyio==3.7.1
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - astor==0.8.1
      - attrs==24.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.0.0
      - cached-property==1.5.2
      - cachetools==5.3.3
      - causalgraphicalmodels==0.0.4
      - cffi==1.15.1
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - comm==0.1.4
      - cplex==22.1.0.0
      - cycler==0.11.0
      - dataclasses==0.6
      - debugpy==1.5.1
      - defusedxml==0.7.1
      - dice-ml==0.5
      - dill==0.3.6
      - docker-pycreds==0.4.0
      - exceptiongroup==1.1.3
      - fastjsonschema==2.21.1
      - fonttools==4.38.0
      - fqdn==1.5.1
      - future==0.18.3
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-pasta==0.2.0
      - grpcio==1.59.0
      - h5py==2.10.0
      - idna==3.6
      - imageio==2.31.2
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - iniconfig==2.0.0
      - ipykernel==6.16.2
      - ipython==7.34.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.16
      - jsonpointer==3.0.0
      - jsonschema==4.17.3
      - jupyter==1.1.1
      - jupyter-client==7.4.9
      - jupyter-console==6.6.3
      - jupyter-core==4.12.0
      - jupyter-events==0.6.3
      - jupyter-server==1.24.0
      - jupyter-server-fileid==0.9.3
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.5
      - jupyterlab==3.6.8
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - jupyterlab-widgets==3.0.13
      - keras==2.3.0
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - lime==0.2.0.1
      - markdown==3.4.4
      - markupsafe==2.1.3
      - matplotlib==3.5.3
      - mip==1.12.0
      - mistune==3.0.2
      - nbclassic==1.1.0
      - nbclient==0.7.4
      - nbconvert==7.6.0
      - nbformat==5.8.0
      - nest-asyncio==1.6.0
      - networkx==2.6.3
      - notebook==6.5.7
      - notebook-shim==0.2.4
      - numpy==1.21.6
      - nvidia-ml-py==12.535.161
      - nvitop==1.3.2
      - packaging==23.2
      - pandas==1.3.5
      - pandocfilters==1.5.1
      - pillow==9.5.0
      - pip==23.3.1
      - pkgutil-resolve-name==1.3.10
      - pluggy==1.2.0
      - prettytable==3.7.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==3.20.3
      - psutil==5.9.6
      - pycparser==2.21
      - pygments==2.16.1
      - pyparsing==3.1.1
      - pyrsistent==0.19.3
      - pytest==7.4.2
      - python-graphviz==0.20.1
      - python-json-logger==3.0.1
      - pytorch-metric-learning==2.3.0
      - pytz==2023.3.post1
      - pywavelets==1.3.0
      - pyyaml==6.0.1
      - recourse==1.0.0
      - recourse-fare==0.1.0
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - scikit-image==0.19.3
      - scikit-learn==1.0.1
      - scipy==1.7.3
      - seaborn==0.12.2
      - send2trash==1.8.3
      - sentry-sdk==1.38.0
      - setproctitle==1.3.3
      - setuptools==68.0.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.4.1
      - style==1.1.0
      - tabulate==0.9.0
      - tensorboard==1.14.0
      - tensorboardx==2.6
      - tensorflow==1.14.0
      - tensorflow-estimator==1.14.0
      - termcolor==2.3.0
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torch==1.12.1
      - torchvision==0.8.1
      - tqdm==4.64.1
      - typing-extensions==4.7.1
      - update==0.0.1
      - uri-template==1.3.0
      - urllib3==2.0.7
      - wandb==0.16.6
      - wcwidth==0.2.8
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.13
      - wrapt==1.15.0
      - xgboost==1.4.2
      - y-py==0.6.2
      - ypy-websocket==0.8.4
      - zipp==3.15.0